### ISSUE TITLE
[BUG?] config menu opens upon foundry load/browser refresh

### ISSUE THREAD

**Issue by MrPotatoZed** [fantasycalendar/FoundryVTT-RestRecovery#64]
After the 1.2.7 update the config menu is opening every time I load foundry or refresh the browser window. It was effective in reminding me to donate for coffee but may be a bit much for most. Confirmed with rest recovery and libwrapper only active. No errors in console.

 - Foundry Version: 9.269
 - System Version: 5e 1.62
 - Rest Recovery Version: 1.2.7
 - Browser & version: Chrome and firefox
 - Hosted on the forge

**Active modules:**
 - Rest Recovery
 - libwrapper

**Comment by Haxxer** [comment]
Try reinstalling the module, you may have gotten a bad version that I accidentally released before I fixed that

**Comment by MrPotatoZed** [comment]
Just reinstalled and still seeing it. Forge has been having weird stuff with mod release tracking so conceivably could be something related to that.

**Comment by MrPotatoZed** [comment]
Ok, just reinstalled from the manifest URL rather than the bazaar listing and it's fixed.

**Comment by MrPotatoZed** [comment]
Good call; forge's bazaar has been super bugged for the last week. Thanks for looking at it.

**Comment by MrPotatoZed** [comment]
Just confirming the bazaar 1.2.8 listing is fixed. Thanks again.
